In [ ]:
# Exercise: 4.1
# Problem - 1: Array Creation:

#1. Initialize an empty array with size 2X2.
import numpy as np

empty_array = np.empty((2, 2))

print("Empty array:")
print(empty_array)


Empty array:
[[0. 0.]
 [0. 0.]]


In [ ]:
#2. Initialize an all one array with size 4X2.
import numpy as np

ones_array = np.ones((4, 2))

print("Array filled with ones:")
print(ones_array)


Array filled with ones:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
import numpy as np

filled_array = np.full((3, 3), 7)

print("Array filled with value 7:")
print(filled_array)


Array filled with value 7:
[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
#4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
import numpy as np

given_array = np.array([[1, 2, 3], [4, 5, 6]])

zeros_array = np.zeros_like(given_array)

print("Original array:")
print(given_array)
print("\nZeros array with the same shape and type:")
print(zeros_array)


Original array:
[[1 2 3]
 [4 5 6]]

Zeros array with the same shape and type:
[[0 0 0]
 [0 0 0]]


In [ ]:
#5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
import numpy as np

given_array = np.array([[1, 2, 3], [4, 5, 6]])

ones_array = np.ones_like(given_array)

print("Original array:")
print(given_array)
print("\nOnes array with the same shape and type:")
print(ones_array)


Original array:
[[1 2 3]
 [4 5 6]]

Ones array with the same shape and type:
[[1 1 1]
 [1 1 1]]


In [ ]:
#6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
import numpy as np

new_list = [1, 2, 3, 4]

array_from_list = np.array(new_list)

print("Original list:")
print(new_list)
print("\nConverted NumPy array:")
print(array_from_list)


Original list:
[1, 2, 3, 4]

Converted NumPy array:
[1 2 3 4]


In [ ]:
# Exercise: 4.1.1
# Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

#1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
import numpy as np

array_range = np.arange(10, 50)

print("Array with values ranging from 10 to 49:")
print(array_range)


Array with values ranging from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#2 Create a 3X3 matrix with values ranging from 0 to 8. {Hint:look for np.reshape()}
import numpy as np

array_range = np.arange(9)

matrix_3x3 = array_range.reshape((3, 3))

print("3x3 matrix with values ranging from 0 to 8:")
print(matrix_3x3)


3x3 matrix with values ranging from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#3 Create a 3X3 identity matrix.{Hint:np.eye()}
import numpy as np

identity_matrix = np.eye(3)

print("3x3 Identity matrix:")
print(identity_matrix)


3x3 Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#4 Create a random array of size 30 and find the mean of the array. {Hint:check for np.random.random() and array.mean() function}

import numpy as np

random_array = np.random.random(30)

mean_value = random_array.mean()

print("Random array of size 30:")
print(random_array)
print("\nMean of the array:")
print(mean_value)


Random array of size 30:
[0.88321288 0.96890028 0.14784562 0.46969717 0.46588175 0.62752485
 0.30634909 0.48006981 0.04405454 0.66367308 0.70538279 0.86355801
 0.93438809 0.75171289 0.63516987 0.18559777 0.8410133  0.82866913
 0.1012203  0.48142433 0.88302409 0.40161454 0.71842283 0.68707217
 0.89077683 0.42971138 0.64045737 0.27360581 0.49438982 0.13608669]

Mean of the array:
0.564683569325836


In [ ]:
#5. Create a 10X10 array with random values and find the minimum and maximum values.
import numpy as np

random_array_10x10 = np.random.random((10, 10))

min_value = random_array_10x10.min()
max_value = random_array_10x10.max()

print("10x10 array with random values:")
print(random_array_10x10)
print("\nMinimum value in the array:", min_value)
print("Maximum value in the array:", max_value)


10x10 array with random values:
[[0.88402593 0.61921967 0.86478517 0.4434559  0.69511906 0.30558821
  0.37130126 0.42215132 0.37884199 0.43609944]
 [0.374939   0.35374933 0.03776884 0.39398848 0.11822041 0.82566594
  0.56839437 0.19000561 0.56100345 0.38246043]
 [0.53814112 0.13420864 0.5911515  0.87762375 0.42657158 0.61142062
  0.13496473 0.22515685 0.16023124 0.85663951]
 [0.12861194 0.54547717 0.90445521 0.44984078 0.78831144 0.80979367
  0.37569204 0.7083712  0.77126545 0.01404284]
 [0.51439277 0.98568782 0.08690432 0.51288406 0.31350907 0.53204635
  0.86156366 0.35910654 0.21179083 0.50393232]
 [0.86072473 0.98319561 0.49705296 0.55609151 0.14319245 0.84829679
  0.03102847 0.72681898 0.36335337 0.43296519]
 [0.36108212 0.73266825 0.52779062 0.89122378 0.84604415 0.36392138
  0.83543915 0.44975019 0.12261122 0.26107158]
 [0.77654071 0.95877344 0.90241538 0.65727531 0.20054609 0.80499259
  0.3185047  0.44956097 0.42282197 0.90750365]
 [0.86217923 0.84618413 0.98714217 0.16396398 0.

In [ ]:
#6. Create a zero array of size 10 and replace 5th element with 1.

import numpy as np
import numpy as np

zero_array = np.zeros(10)

zero_array[4] = 1

print("Array with the 5th element replaced by 1:")
print(zero_array)


Array with the 5th element replaced by 1:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#7. Reverse an array arr = [1,2,0,0,4,0].

import numpy as np
array = np.array([1,2,0,0,4,0])
reversed_array= array[::-1]
print("Original array: ",array)
print("Reversed array: ",reversed_array)

Original array:  [1 2 0 0 4 0]
Reversed array:  [0 4 0 0 2 1]


In [ ]:
#8 Create a 2d array with 1 on border and 0 inside.
import numpy as np

size = 5

array = np.zeros((size, size))

array[0, :] = 1
array[-1, :] = 1
array[:, 0] = 1
array[:, -1] = 1

print("2D array with 1 on border and 0 inside:")
print(array)


2D array with 1 on border and 0 inside:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#9  Create a 8X8 matrix and fill it with a checkerboard pattern.

import numpy as np

checkerboard = np.zeros((8, 8), dtype=int)

checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print("8x8 Checkerboard pattern:")
print(checkerboard)


8x8 Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
# Problem - 3: Array Operations:

#1. Add the two array.import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

sum_array = np.add(x, y)

print("Sum of the two arrays:")
print(sum_array)


Sum of the two arrays:
[[ 6  8]
 [10 13]]


In [ ]:
#2 Subtract the two array.
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

difference_array = np.subtract(x, y)

print("Difference of the two arrays:")
print(difference_array)


Difference of the two arrays:
[[-4 -4]
 [-4 -3]]


In [ ]:
#3 Multiply the array with any integers of your choice.
import numpy as np

x = np.array([[1, 2], [3, 5]])

result = x * 3

print("Array after multiplying by 3:")
print(result)


Array after multiplying by 3:
[[ 3  6]
 [ 9 15]]


In [ ]:
#4 Find the square of each element of the array.
import numpy as np

# Define the array
x = np.array([[1, 2], [3, 5]])

# Square each element of the array
squared_array = x ** 2

print("Array with the square of each element:")
print(squared_array)


Array with the square of each element:
[[ 1  4]
 [ 9 25]]


In [ ]:
#5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

print("Dot product of v and w: \n", np.dot(v,w), "\n")
print("Dot product of x and v: \n", np.dot(x,v), "\n")
print("Dot product of x and y: \n", np.dot(x,y), "\n")

Dot product of v and w: 
 219 

Dot product of x and v: 
 [29 77] 

Dot product of x and y: 
 [[19 22]
 [50 58]] 



In [ ]:
#6. Concatenate x(and)y along row and Concatenate v(and)w along column. {Hint:try np.concatenate() or np.vstack() functions.

import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_col = np.vstack((v, w))

print("Concatenate x and y along rows:\n",concat_xy_row)
print("Concatenate v and w along colums:\n",concat_vw_col)

Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along colums:
 [[ 9 10]
 [11 12]]


In [ ]:
#7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

import numpy as np
x = np.array([[1,2],[3,5]])
v = np.array([9,10])
concat_xv = np.concatenate(x,v)
print(concat_xv)

#An error occured because the dimensions along the axis being concatenated must align.

In [ ]:
# Problem - 4: Matrix Operations:

import numpy as np

# Given matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A.A⁻¹ = I
A_inv = np.linalg.inv(A)
I = np.eye(2)
print("Multiplication of A and inverse of A):")
print(np.dot(A, A_inv))
print("\nIdentity matrix:")
print(I)

# 2. Prove AB ≠ BA
AB = np.dot(A,B)
print("A.B : \n", AB, "\n")
BA = np.dot(B,A)
print("B.A : \n", BA, "\n")
print("AB == BA ? : ", np.allclose(AB,BA), "\n")

# 3. Prove (AB)ᵀ = BᵀAᵀ
trans_of_AB = np.transpose(AB)
print("Transpose of AB: \n",trans_of_AB, "\n")
trans_of_B = np.transpose(B)
trans_of_A = np.transpose(A)
A_trans_b_trans = np.dot(trans_of_B, trans_of_A)
print("A transpose.B transpose : \n", A_trans_b_trans, "\n")
print("Is (AB)ᵀ equal to BᵀAᵀ ?: ", np.allclose(trans_of_AB, A_trans_b_trans), "\n")

Multiplication of A and inverse of A):
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Identity matrix:
[[1. 0.]
 [0. 1.]]
A.B : 
 [[23 13]
 [51 29]] 

B.A : 
 [[36 44]
 [13 16]] 

AB == BA ? :  False 

Transpose of AB: 
 [[23 51]
 [13 29]] 

A transpose.B transpose : 
 [[23 51]
 [13 29]] 

Is (AB)ᵀ equal to BᵀAᵀ ?:  True 



In [1]:
# Solve the following system of Linear equation using Inverse Methods.
# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9

# {Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

import numpy as np

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

# Step 1: Determinant of A
det_A = (A[0, 0] * (A[1, 1] * A[2, 2] - A[1, 2] * A[2, 1]) -
         A[0, 1] * (A[1, 0] * A[2, 2] - A[1, 2] * A[2, 0]) +
         A[0, 2] * (A[1, 0] * A[2, 1] - A[1, 1] * A[2, 0]))

print("Determinant of A:", det_A)

# Step 2: Cofactor matrix
cofactor_matrix = np.array([
    [(A[1, 1] * A[2, 2] - A[1, 2] * A[2, 1]), -(A[1, 0] * A[2, 2] - A[1, 2] * A[2, 0]), (A[1, 0] * A[2, 1] - A[1, 1] * A[2, 0])],
    [-(A[0, 1] * A[2, 2] - A[0, 2] * A[2, 1]), (A[0, 0] * A[2, 2] - A[0, 2] * A[2, 0]), -(A[0, 0] * A[2, 1] - A[0, 1] * A[2, 0])],
    [(A[0, 1] * A[1, 2] - A[0, 2] * A[1, 1]), -(A[0, 0] * A[1, 2] - A[0, 2] * A[1, 0]), (A[0, 0] * A[1, 1] - A[0, 1] * A[1, 0])]
])

# Step 3: Adjoint of A (transpose of cofactor matrix)
adjoint_A = cofactor_matrix.T

# Step 4: Inverse of A
inverse_A = adjoint_A / det_A
print("\nInverse of A:\n", inverse_A)

# Step 5: X = A⁻¹B
X = np.dot(inverse_A, B)
print("\nSolution (x, y, z):", X)


Determinant of A: -19

Inverse of A:
 [[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]

Solution (x, y, z): [ 2.  1. -2.]


In [ ]:
# Solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function of Numpy}
import numpy as np

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

# Inverse of A using np.linalg.inv
A_inv = np.linalg.inv(A)

# X = A⁻¹B
X = np.dot(A_inv, B)

print("Inverse of A:\n", A_inv)
print("\nSolution (x, y, z):", X)

Inverse of A:
 [[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]

Solution (x, y, z): [ 2.  1. -2.]


In [ ]:
# 4.2 Experiment: How Fast is Numpy?

# 1. Element-wise Addition:

import time

list1=[i for i in range(1,100000)]
list2=[j for j in range(1,100000)]

print("1. Element-wise Addition: \n")
start_at = time.time()
sum1 = [list1[i] + list2[i] for i in range(len(list1))]
end_at = time.time()
print("Time taken for this operation using Python Lists is: ", end_at-start_at, "seconds.\n")


arr1 = np.arange(1_000_000)
arr2 = np.arange(1_000_000)

start_at = time.time()
sum2 = arr1 + arr2
end_at = time.time()
print("Time taken for this operation using NumPy Arrays is:", end_at - start_at, "seconds.")

1. Element-wise Addition: 

Time taken for this operation using Python Lists is:  0.01770496368408203 seconds.

Time taken for this operation using NumPy Arrays is: 0.0043408870697021484 seconds.


In [ ]:
# 2. Element-wise Multiplication:

list1=[i for i in range(1,100000)]
list2=[j for j in range(1,100000)]

print("Element-wise Multiplicatio: \n")
start_at = time.time()
product1 = [list1[i] * list2[i] for i in range(len(list1))]
end_at = time.time()
print("Time taken for this operation using Python Lists is: ", end_at-start_at, "seconds.\n")


arr1 = np.arange(1_000_000)
arr2 = np.arange(1_000_000)

start_at = time.time()
product2 = arr1*arr2
end_at = time.time()
print("Time taken for this operation using NumPy Arrays is:", end_at - start_at, "seconds")

Element-wise Multiplicatio: 

Time taken for this operation using Python Lists is:  0.03302431106567383 seconds.

Time taken for this operation using NumPy Arrays is: 0.003694772720336914 seconds


In [ ]:
# 3. Dot Product :
list1=[i for i in range(1,100000)]
list2=[j for j in range(1,100000)]

print("Dot product: \n")
start_at = time.time()
product1 = [list1[i] * list2[i] for i in range(len(list1))]
end_at = time.time()
print("Time taken for this operation using Python Lists is: ", end_at-start_at, "seconds.\n")


arr1 = np.arange(1_000_000)
arr2 = np.arange(1_000_000)

start_at = time.time()
product2 = np.dot(arr1, arr2)
end_at = time.time()
print("Time taken using NumPy arrays:", end_at - start_at, "seconds")

Dot product: 

Time taken for this operation using Python Lists is:  0.016830921173095703 seconds.

Time taken using NumPy arrays: 0.0015478134155273438 seconds


In [ ]:
# 4. Matrix Multiplication
print("4. Matrix Multiplication")
size = 100

# Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.
matrix1 = [[i for i in range(size)] for _ in range(size)]
matrix2 = [[j for j in range(size)] for _ in range(size)]

start_time = time.time()
result_matrix = [[sum(a * b for a, b in zip(row, col)) for col in zip(*matrix2)] for row in matrix1]
end_time = time.time()
print(f"Time taken by Python Lists: {end_time - start_time:.5f} seconds")

# Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.
matrix1_np = np.array(matrix1)
matrix2_np = np.array(matrix2)

start_time = time.time()
result_matrix_np = np.dot(matrix1_np, matrix2_np)
end_time = time.time()
print(f"Time taken by numpy: {end_time - start_time:.5f} seconds")

4. Matrix Multiplication
Time taken by Python Lists: 0.11889 seconds
Time taken by numpy: 0.00135 seconds
